// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1boqLmBY0jTpJnRljD9geMpjk62f5mc',
    appId: '1:979818462070:web:a940e809d6a1954a149857',
    messagingSenderId: '979818462070',
    projectId: 'this-chat-app-57304',
    authDomain: 'this-chat-app-57304.firebaseapp.com',
    storageBucket: 'this-chat-app-57304.appspot.com',
    measurementId: 'G-KTZR19TKFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpNX67oKrRlmk2cToxx7dmPN7GBNqOBo',
    appId: '1:979818462070:android:ab68c4b0956ff9a5149857',
    messagingSenderId: '979818462070',
    projectId: 'this-chat-app-57304',
    storageBucket: 'this-chat-app-57304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJvLYjNFBYhZ6L-wzA5pKv8NO5ZJzxIU',
    appId: '1:979818462070:ios:d77f45392d0dfe92149857',
    messagingSenderId: '979818462070',
    projectId: 'this-chat-app-57304',
    storageBucket: 'this-chat-app-57304.appspot.com',
    iosClientId: '979818462070-i4k6nr0etm0tv46m2lb35vgoamgtb5l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJvLYjNFBYhZ6L-wzA5pKv8NO5ZJzxIU',
    appId: '1:979818462070:ios:d77f45392d0dfe92149857',
    messagingSenderId: '979818462070',
    projectId: 'this-chat-app-57304',
    storageBucket: 'this-chat-app-57304.appspot.com',
    iosClientId: '979818462070-i4k6nr0etm0tv46m2lb35vgoamgtb5l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
